### ISSUE TITLE
NullPointerException when calling goals explicitly

### ISSUE THREAD

**Issue by chrisdutz** [khmarbaise/maven-buildtime-profiler#8]
In my current project I'm doing a Maven build like this:

    mvn clean install site site:stage

It seems the "site:stage" in the end causes a NPE in MojoTimer.java (110) as the collection of phases lifeCyclePhases in BuildTimeProfiller line 394 contains "null" values. Simply adding an "If" check could avoid the error, but I think in this case eventually the code would have to be adjusted to output also stats for the goals not bound to a lifecycle phase.

**Comment by khmarbaise** [comment]
@chrisdutz Can you check if everything is now ok after fixing the issue? Thanks for reporting this...
